#!/bin/bash

# Creates binary folder.
if [ ! -d "/usr/local/codejam" ]
then
	mkdir /usr/local/codejam
fi

# Downloading latest version.
curl -o /usr/local/codejam/googlecodejam-client.jar -J -L "https://github.com/Faylixe/googlecodejam-client/releases/download/v1.0.0/googlecodejam-client.jar"
chmod o+rx /usr/local/codejam/googlecodejam-client.jar

# Install script.
wget -P /usr/bin "https://raw.githubusercontent.com/Faylixe/googlecodejam-client/master/scripts/codejam"
chmod o+rx /usr/bin/codejam
